spring.application.name=Ecommerce-Shopping-Platform

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://ssdineshkarthick_db_user:Dinesh%402005@cluster0.eiqjysr.mongodb.net/ecommerce_store?retryWrites=true&w=majority&appName=Cluster0

# MongoDB connection timeout settings
spring.data.mongodb.connection-timeout=10000
spring.data.mongodb.socket-timeout=10000
